---
# Security groups

- name: "Secgroups - Setting global security groups"
  include: secgroup.yml
  with_items: "{{ cf_security_groups | default([]) }}"
  loop_control:
    loop_var: cf_secgroup
  delegate_to: "{{ groups.client[0] }}"

- name: "Secgroups - Managing staging default security groups"
  cf_config:
    type: sec_group
    context: "staging"
    name: "{{ item.name }}"
    state: "{{ item.staging_default | default(true) | bool | ternary('present','absent') }}"
    admin_user: "{{ cf_admin_user }}"
    admin_password: "{{ cf_admin_password }}"
    api_url: "{{ cf_api }}"
  when: >
    item.state is not defined or (item.state is defined and item.state == 'present')
  with_items: "{{ cf_security_groups | default([]) }}"

- name: "Secgroups - Managing running default security groups"
  cf_config:
    type: sec_group
    context: "running"
    name: "{{ item.name }}"
    state: "{{ item.running_default | default(true) | bool | ternary('present','absent') }}"
    admin_user: "{{ cf_admin_user }}"
    admin_password: "{{ cf_admin_password }}"
    api_url: "{{ cf_api }}"
  when: >
    item.state is not defined or (item.state is defined and item.state == 'present')
  with_items: "{{ cf_security_groups | default([]) }}"

